{
 "title": "Xinfra",
 "description": "External monitoring of Kafka",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } }
  ]
 },
 "panels": [
  { "title": "Producer Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Produce Latency - Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_produce_service_produce_delay_ms_avg{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Produce Latency - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_produce_service_produce_delay_ms_99th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Produce Latency - p999",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_produce_service_produce_delay_ms_999th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Produce Latency - p9999",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_produce_service_produce_delay_ms_9999th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Produce Latency - Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_produce_service_produce_delay_ms_max{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  { "title": "End-To-End Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "End-To-End Latency - Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_avg{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "End-To-End Latency - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_99th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "End-To-End Latency - p999",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_999th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "End-To-End Latency - p9999",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_9999th{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "End-To-End Latency - Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kmf_services_consume_service_records_delay_ms_max{job=\"xinfra\",env=\"$env\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Consumer Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offset Commit Latency - Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_commit_latency_service_commit_offset_latency_ms_avg{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Offset Commit Latency - p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_commit_latency_service_commit_offset_latency_ms_99th{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Offset Commit Latency - p999",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_commit_latency_service_commit_offset_latency_ms_999th{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Offset Commit Latency - p9999",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_commit_latency_service_commit_offset_latency_ms_9999th{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Offset Commit Latency - Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_commit_latency_service_commit_offset_latency_ms_max{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Offset Commits - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_commit_availability_service_offsets_committed_avg{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Offset Commits Failed - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_commit_availability_service_failed_commit_offsets_avg{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "End-To-End Latency SLAs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records Breaching SLA - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_consume_service_records_delayed_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Duplicated / Lost Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Records Produced - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_produce_service_records_produced_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Records Produced - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_produce_service_records_produced_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Records Duplicated - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_consume_service_records_duplicated_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Records Lost - Avg/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_consume_service_records_lost_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Producer Errors Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_produce_service_produce_error_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Average Consumer Errors Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kmf_services_consume_service_consume_error_rate{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Count"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic Management Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Topic Create Time - Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_cluster_topic_manipulation_service_topic_creation_metadata_propagation_ms_avg{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Topic Create Time - Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_cluster_topic_manipulation_service_topic_creation_metadata_propagation_ms_max{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Topic Delete Time - Avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_cluster_topic_manipulation_service_topic_deletion_metadata_propagation_ms_avg{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    },
    {
     "title": "Topic Delete Time - Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kmf_services_cluster_topic_manipulation_service_topic_deletion_metadata_propagation_ms_max{job=\"xinfra\",env=\"$env\"}",
       "legendFormat": "Latency"
      }
     ]
    }
   ]
  }
 ]
}