---
version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:VERSION
    restart: on-failure:3
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9999:/volumes/zookeeper.yml
    volumes:
      - /tmp/cpdocker/volumes/zookeeper:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-txn-logs:/var/lib/zookeeper/log
  
  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:VERSION
    hostname: kafka1
    ports:
      - 9092:9092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9996:/volumes/kafka_broker.yml
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
      - kafka1-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:VERSION
    hostname: kafka2
    ports:
      - 19092:19092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:19092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9995:/volumes/kafka_broker.yml
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
      - kafka2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafka3:
    container_name: kafka3
    image: confluentinc/cp-kafka:VERSION
    hostname: kafka3
    ports:
      - 29092:29092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9994:/volumes/kafka_broker.yml
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
      - kafka3-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  schemaregistry:
    image: confluentinc/cp-schema-registry:VERSION
    container_name: schemaregistry
    hostname: schemaregistry
    ports:
      - 8081:8081
    restart: on-failure:3
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9993:/volumes/confluent_schemaregistry.yml
    volumes:
      - /tmp/cpdocker/volumes/schemaregistry:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  connect:
    image: confluentinc/cp-kafka-connect:VERSION
    container_name: connect
    restart: on-failure:3
    hostname: connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_LISTENERS: http://0.0.0.0:8083
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/volumes
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      EXTRA_ARGS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9992:/volumes/kafka_connect.yml
    volumes:
      - /tmp/cpdocker/volumes/connect:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
      - kafka-connect:/usr/share/confluent-hub-components
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  ksqldb:
    container_name: ksqldb
    image: confluentinc/cp-ksqldb-server:VERSION
    hostname: ksqldb
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      KSQL_KSQL_SERVICE_ID: ksqldb
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schemaregistry:8081
      KSQL_OPTS: -javaagent:/jmxexporter/jmx_prometheus_javaagent-0.17.0.jar=9990:/volumes/confluent_ksql.yml
    volumes:
      - /tmp/cpdocker/volumes/ksqldb:/volumes
      - /tmp/cpdocker/volumes/jmxexporter:/jmxexporter
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - schemaregistry

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /tmp/cpdocker/volumes/prometheus/:/etc/prometheus

  grafana:
    image: grafana/grafana:9.0.2
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - /tmp/cpdocker/volumes/grafana/:/etc/grafana/provisioning

volumes:
  zookeeper-data:
  zookeeper-txn-logs:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  kafka-connect:
