---
version: '3.8'
services:
  zookeeper1:
    container_name: zookeeper1
    image: confluentinc/cp-zookeeper:VERSION
    restart: on-failure:3
    hostname: zookeeper1
    ports:
      - 2181:2181
      - 2888:2888
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:12888:13888;zookeeper3:22888:23888
      KAFKA_JMX_PORT: 9999
    volumes:
      - zookeeper1-data:/var/lib/zookeeper/data
      - zookeeper1-txn-logs:/var/lib/zookeeper/log

  zookeeper2:
    container_name: zookeeper2
    image: confluentinc/cp-zookeeper:VERSION
    restart: on-failure:3
    hostname: zookeeper2
    ports:
      - 12181:12181
      - 12888:12888
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:12888:13888;zookeeper3:22888:23888
      KAFKA_JMX_PORT: 9998
    volumes:
      - zookeeper2-data:/var/lib/zookeeper/data
      - zookeeper2-txn-logs:/var/lib/zookeeper/log

  zookeeper3:
    container_name: zookeeper3
    image: confluentinc/cp-zookeeper:VERSION
    restart: on-failure:3
    hostname: zookeeper3
    ports:
      - 22181:22181
      - 22888:22888
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:12888:13888;zookeeper3:22888:23888
      KAFKA_JMX_PORT: 9997
    volumes:
      - zookeeper3-data:/var/lib/zookeeper/data
      - zookeeper3-txn-logs:/var/lib/zookeeper/log

  kafka1:
    container_name: kafka1
    image: localbuild/cp-kafka-custom:VERSION
    hostname: kafka1
    ports:
      - 9092:9092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:12181,zookeeper3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      KAFKA_JMX_PORT: 9996
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - kafka1-data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    container_name: kafka2
    image:  localbuild/cp-kafka-custom:VERSION
    hostname: kafka2
    ports:
      - 19092:19092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:12181,zookeeper3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:19092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      KAFKA_JMX_PORT: 9995
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - kafka2-data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    container_name: kafka3
    image:  localbuild/cp-kafka-custom:VERSION
    hostname: kafka3
    ports:
      - 29092:29092
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:12181,zookeeper3:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29092
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: state.change.logger=INFO
      KAFKA_JMX_PORT: 9994
    volumes:
      - /tmp/cpdocker/volumes/kafka:/volumes
      - kafka3-data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  schemaregistry:
    image: confluentinc/cp-schema-registry:VERSION
    container_name: schemaregistry
    hostname: schemaregistry
    ports:
      - 8081:8081
    restart: on-failure:3
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: none
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_JMX_PORT: 9993
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  connect:
    image: confluentinc/cp-kafka-connect:VERSION
    container_name: connect
    restart: on-failure:3
    hostname: connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_LISTENERS: http://0.0.0.0:8083
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-statuses
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      KAFKA_JMX_PORT: 9992
    volumes:
      - kafka-connect:/usr/share/confluent-hub-components
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  restproxy:
    image: confluentinc/cp-kafka-rest:VERSION
    ports:
      - 8082:8082
    hostname: restproxy
    container_name: restproxy
    environment:
      KAFKA_REST_HOST_NAME: restproxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_JMX_PORT: 9991
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  controlcenter:
    container_name: controlcenter
    image: confluentinc/cp-enterprise-control-center:VERSION
    hostname: controlcenter
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      CONTROL_CENTER_REPLICATION_FACTOR: 3
      PORT: 9021
    volumes:
      - confluent-control-center:/var/lib/confluent-control-center
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  ksqldb:
    container_name: ksqldb
    image: confluentinc/cp-ksqldb-server:VERSION
    hostname: ksqldb
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:19092,kafka3:29092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_STREAMS_STATE_DIR: /var/lib/ksqldb
      KSQL_JMX_PORT: 9990
    volumes:
      - ksqldb:/var/lib/ksqldb
    depends_on:
      - kafka1
      - kafka2
      - kafka3

volumes:
  zookeeper1-data:
  zookeeper1-txn-logs:
  zookeeper2-data:
  zookeeper2-txn-logs:
  zookeeper3-data:
  zookeeper3-txn-logs:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  kafka-connect:
  confluent-control-center:
  ksqldb:
